// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBucKLJrbEa0QXg4z7gq-XIfWAMA9sdMtY',
    appId: '1:134254458624:web:5e57560277aff52060e5e5',
    messagingSenderId: '134254458624',
    projectId: 'cw-7-e0c38',
    authDomain: 'cw-7-e0c38.firebaseapp.com',
    storageBucket: 'cw-7-e0c38.firebasestorage.app',
    measurementId: 'G-BWD6NBRJYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1bAuEBeXVYI9Wumz59RxeQ4pdz54XMx0',
    appId: '1:134254458624:android:ba25dee4d14fc67960e5e5',
    messagingSenderId: '134254458624',
    projectId: 'cw-7-e0c38',
    storageBucket: 'cw-7-e0c38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMAJZ7HTUHqVB6Z61G2gUoV8u95nwuDfQ',
    appId: '1:134254458624:ios:c21cb969d7d5064160e5e5',
    messagingSenderId: '134254458624',
    projectId: 'cw-7-e0c38',
    storageBucket: 'cw-7-e0c38.firebasestorage.app',
    iosBundleId: 'com.example.fcmDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMAJZ7HTUHqVB6Z61G2gUoV8u95nwuDfQ',
    appId: '1:134254458624:ios:c21cb969d7d5064160e5e5',
    messagingSenderId: '134254458624',
    projectId: 'cw-7-e0c38',
    storageBucket: 'cw-7-e0c38.firebasestorage.app',
    iosBundleId: 'com.example.fcmDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBucKLJrbEa0QXg4z7gq-XIfWAMA9sdMtY',
    appId: '1:134254458624:web:f2fe5cd55832d9cf60e5e5',
    messagingSenderId: '134254458624',
    projectId: 'cw-7-e0c38',
    authDomain: 'cw-7-e0c38.firebaseapp.com',
    storageBucket: 'cw-7-e0c38.firebasestorage.app',
    measurementId: 'G-CYHCFY1XFS',
  );
}
